version: '2'
services:
    dungeonmart-app:
        image: dungeonmart
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://dungeonmart-postgresql:5432/dungeonmart
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=dungeonmart-elasticsearch:9300
        ports:
            - 8080:8080
    dungeonmart-postgresql:
        extends:
            file: postgresql.yml
            service: dungeonmart-postgresql
    dungeonmart-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: dungeonmart-elasticsearch
