version: '2'
services:
    dungeonmart-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/dungeonmart/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=dungeonmart
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
